services:
  boarding-pass:
    build:
      context: .
      dockerfile: .Dockerfile
      args:
        NODE_VERSION: 22
        GO_VERSION: 1.26
    environment:
      VITE_API_ENDPOINT: http://localhost:8080/api
    image: boarding-pass:local
    ports:
      - "8080:8080"
    volumes:
      - ./backend/config.json:/app/backend/config.json:ro
      - ./local-secrets:/app/local-secrets:ro
    restart: unless-stopped
